# Generated by Django 2.0 on 2020-11-29 01:48

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estudo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, null=True)),
                ('nome', models.CharField(blank=True, max_length=180, null=True, verbose_name='Nome do estudo de caso.')),
                ('trabalho_feito', models.CharField(blank=True, max_length=260, null=True, verbose_name='Trabalho realizado')),
                ('cliente', models.CharField(blank=True, max_length=260, null=True, verbose_name='Nome do cliente')),
                ('titulo_cliente', models.CharField(blank=True, max_length=260, null=True, verbose_name='Titulo do cliente')),
                ('depoimento', models.TextField(blank=True, null=True, verbose_name='Depoimento do cliente')),
                ('breve_descricao', models.TextField(blank=True, null=True, verbose_name='Breve descrição do estudo de caso.')),
                ('descricao_detalhada', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Descrição detalhada do estudo de caso.')),
                ('servico_imagem', models.ImageField(default='', upload_to='uploads/estudos/%Y/%m/', verbose_name='Imagem do estudo (600X1900)')),
            ],
            options={
                'verbose_name_plural': 'Estudos de caso.',
            },
        ),
    ]
