# Generated by Django 2.0 on 2020-11-29 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estudo',
            old_name='servico_imagem',
            new_name='estudo_imagem',
        ),
    ]
