# Generated by Django 2.0 on 2020-11-15 23:37

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=180, null=True, verbose_name='Nome do serviço.')),
                ('breve_descricao', models.TextField(blank=True, null=True, verbose_name='Breve descrição do serviço.')),
                ('descricao_detalhada', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Descrição detalhada do serviço.')),
                ('servico_imagem', models.ImageField(default='', upload_to='uploads/servicos/%Y/%m/', verbose_name='Imagem do serviço (630X550)')),
            ],
            options={
                'verbose_name_plural': 'Serviços oferecidos',
            },
        ),
    ]
