# Generated by Django 2.0 on 2020-11-29 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servico',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
