# Generated by Django 2.0 on 2020-09-13 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conquista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=160, verbose_name='Descriçao da conquista (e.g. Mais de 20 projetos executados)')),
            ],
        ),
        migrations.CreateModel(
            name='EstudoDeCaso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=160, verbose_name='Título do serviço')),
                ('trabalho_realizado', models.TextField(verbose_name='Trabalho realizado')),
                ('breve_descricao', models.TextField(verbose_name='Breve descrição do serviço realizado')),
                ('imagem', models.ImageField(default='', upload_to='uploads/estudos/%Y/%m/', verbose_name='Foto de divulgação do serviço (650x500)')),
            ],
        ),
        migrations.CreateModel(
            name='PaginaContato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Informações que estão presentes na página de contato.', max_length=80, verbose_name='Título')),
                ('cidade', models.CharField(max_length=160, verbose_name='Cidade que o escritório está localizado')),
                ('rua', models.CharField(max_length=160, verbose_name='Rua que o escritório está localizado')),
                ('bairro', models.CharField(max_length=160, verbose_name='Bairro que o escritório está localizado')),
                ('cep', models.CharField(max_length=160, verbose_name='CEP que o escritório está localizado')),
                ('numero', models.CharField(max_length=160, verbose_name='Numero que o escritório está localizado')),
                ('telefone', models.CharField(max_length=160, verbose_name='Telefone para contato do escritório')),
                ('email', models.EmailField(max_length=254, verbose_name='Email para contato.')),
                ('imagem_escritório', models.ImageField(default='', upload_to='uploads/servicos/%Y/%m/', verbose_name='Foto de divulgação do serviço (650x400)')),
            ],
        ),
        migrations.CreateModel(
            name='PaginaHome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Informações que estão presentes na página home.', max_length=80, verbose_name='Título')),
                ('slogan', models.CharField(max_length=160, verbose_name='Slogan da empresa')),
                ('sobre_titulo', models.CharField(max_length=160, verbose_name='Sobre titulo')),
                ('sobre_descricao', models.TextField(verbose_name='Sobre descrição')),
                ('sobre_time', models.ImageField(default='', upload_to='uploads/home/%Y/%m/', verbose_name='Foto do time divulgação (100x100)')),
            ],
            options={
                'verbose_name_plural': 'Pagina Home',
            },
        ),
        migrations.CreateModel(
            name='PaginaServico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Informações que estão presentes na página de serviços.', max_length=80, verbose_name='Título')),
                ('titulo', models.CharField(max_length=160, verbose_name='Titulo')),
                ('descricao', models.TextField(verbose_name='Descrição')),
            ],
        ),
        migrations.CreateModel(
            name='PaginaSobre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Informações que estão presentes na página sobre.', max_length=80, verbose_name='Título')),
                ('titulo', models.CharField(max_length=160, verbose_name='Titulo')),
                ('sobre_descricao', models.TextField(verbose_name='Descrição')),
            ],
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=160, verbose_name='Título do serviço')),
                ('descricao', models.TextField(verbose_name='Descrição do serviço')),
                ('imagem', models.ImageField(default='', upload_to='uploads/servicos/%Y/%m/', verbose_name='Foto de divulgação do serviço (400x350)')),
            ],
        ),
    ]
