# Generated by Django 2.0 on 2020-11-14 20:36

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paginahome',
            name='sobre_descricao',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Sobre descrição'),
        ),
    ]
