# Generated by Django 2.0 on 2020-11-15 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20201114_2036'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Servico',
        ),
    ]
